# Book settings
title: "TeDCog Handbook"
author: TeDCog members
#logo: https://i.imgur.com/qLltTCl.jpeg
url: "http://tedcog.github.io/handbook"

html:
    extra_navbar: |
        <div>
            Handbook created using <a href="https://github.com/very-good-science/our-meta-handbook">Our Handbook</a>.
            Powered by <a href="https://jupyterbook.org/">Jupyter Book</a>.
        </div>
    favicon: "favicon.ico"

sphinx:
    extra_extensions:
        - sphinx_inline_tabs
    extra_footer: |
        <p>
            License: <a href="https://creativecommons.org/licenses/by/3.0/legalcode">CC-BY 3.0</a>
        </p>
    config:
        html_show_copyright: false
        html_last_updated_fmt: "%Y-%m-%d (%H:%M %Z)" 

